[project]
name = "skylake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dbt-spark[pyhive]>=1.11.0",
    "jupyter>=1.1.1",
    "pyspark~=4.0.4",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "apache-airflow==2.10.5",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
